# Generated by Django 3.2.12 on 2023-02-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
    ]
